/// Flutter icons ChessIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ChessIcon
///      fonts:
///       - asset: fonts/ChessIcon.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ChessIcon {
  ChessIcon._();

  static const _kFontFam = 'ChessIcon';
  static const String? _kFontPkg = null;

  static const IconData chess_bishop = IconData(0xf43a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_king = IconData(0xf43f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_knight = IconData(0xf441, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_pawn = IconData(0xf443, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_queen = IconData(0xf445, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_rook = IconData(0xf447, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
